# Generated by Django 5.2.7 on 2025-10-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Father'), ('staff', 'Parish Staff'), ('family_head', 'Family Head'), ('unit_president', 'Family Unit President'), ('group_leader', 'Group Leader'), ('provincial', 'Provincial'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
