# Generated by Django 5.2.7 on 2026-02-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parish', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('about', models.TextField(blank=True)),
            ],
        ),
    ]
