# Generated by Django 5.2.7 on 2026-02-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parish', '0003_galleryimage_created_by_galleryimage_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='parish',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='parish/'),
        ),
        migrations.AddField(
            model_name='parish',
            name='mass_timings',
            field=models.TextField(blank=True, help_text='Example: Sunday 7:00 AM & 9:30 AM | Weekdays 6:30 AM'),
        ),
        migrations.AddField(
            model_name='parish',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='parish',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
