# Generated by Django 5.2.7 on 2026-02-20 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parish', '0004_parish_logo_parish_mass_timings_parish_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParishLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('vicar', 'Vicar (വികാരി)'), ('kaikaran', 'Kaikaran (കൈക്കാരൻ)'), ('secretary', 'Secretary (സെക്രട്ടറി)'), ('church_servant', 'Church Servant (ദേവാലയ ശുശ്രൂഷി)')], max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='parish/leaders/')),
                ('term_start', models.DateField()),
                ('term_end', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='parish.parish')),
            ],
        ),
    ]
