# Generated by Django 5.2.7 on 2026-02-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parish', '0005_parishleader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parishleader',
            name='term_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
