# Generated by Django 5.2.7 on 2026-03-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parish', '0006_alter_parishleader_term_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
