# Generated by Django 5.2.7 on 2026-03-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parish', '0007_alter_galleryimage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parishleader',
            name='role',
            field=models.CharField(choices=[('vicar', 'Vicar (വികാരി)'), ('kaikaran', 'Kaikaran (കൈക്കാരൻ)'), ('secretary', 'Secretary (സെക്രട്ടറി)'), ('church_servant', 'Church Servant (ദേവാലയ ശുശ്രൂഷി)'), ('provincial', 'Provincial (പ്രൊവിൻഷ്യൽ)'), ('vice_chairman', 'Vice Chairman (വൈസ് ചെയർമാൻ)')], max_length=50),
        ),
    ]
