# Generated by Django 5.2.7 on 2025-10-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParishGroup',
        ),
        migrations.AlterField(
            model_name='familymember',
            name='parish_groups',
            field=models.ManyToManyField(blank=True, related_name='members', to='groups.parishgroup'),
        ),
    ]
