# Generated by Django 5.2.7 on 2026-02-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0002_delete_parishgroup_alter_familymember_parish_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='user',
        ),
        migrations.AddField(
            model_name='familymember',
            name='is_family_head',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familymember',
            name='name',
            field=models.CharField(default='Member', max_length=150),
            preserve_default=False,
        ),
    ]
