# Generated by Django 5.2.7 on 2026-03-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0003_remove_familymember_user_familymember_is_family_head_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyunit',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='units/logos/'),
        ),
    ]
