# Generated by Django 5.2.7 on 2026-03-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0004_familyunit_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='relation',
            field=models.CharField(blank=True, choices=[('son', 'മകൻ'), ('daughter', 'മകൾ'), ('son_in_law', 'മരുമകൻ'), ('daughter_in_law', 'മരുമകൾ'), ('wife', 'ഭാര്യ'), ('husband', 'ഭർത്താവ്')], max_length=20, null=True),
        ),
    ]
