# Generated by Django 5.2.7 on 2026-03-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parishgroup',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='groups/logos/'),
        ),
    ]
